### PR TITLE
snap: add missing install hook

### LINKED ISSUE #11: Daemon fails to enable by default on Ubuntu Core
Using:

```
ubuntu-frame       116-mir2.15.0+dev135    6989   22/edge        canonical✓  -
ubuntu-frame-vnc   43-wayvncv0.6.2         211    22/stable      canonical✓  -
```

Following:

https://mir-server.io/docs/how-to-use-remote-assistance-with-ubuntu-frame#heading--the-ubuntu-frame-vnc-snap--using-as-a-daemon

Which notes:

> The default on Ubuntu Core, using as a daemon allows you to always have the remote access enabled.

On a fresh install of `22/stable`, the logs show:

```
2023-10-02T21:37:26Z systemd[1]: Started Service for snap application ubuntu-frame-vnc.daemon.
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3205]: + snapctl get daemon
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3161]: + [  = true ]
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3161]: + snapctl stop ubuntu-frame-vnc.daemon
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3210]: error: error running snapctl: snap "ubuntu-frame-vnc" has "install-snap" change in progress
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3161]: + true
2023-10-02T21:37:26Z systemd[1]: snap.ubuntu-frame-vnc.daemon.service: Deactivated successfully.
2023-10-02T21:37:26Z systemd[1]: snap.ubuntu-frame-vnc.daemon.service: Scheduled restart job, restart counter is at 1.
2023-10-02T21:37:26Z systemd[1]: Stopped Service for snap application ubuntu-frame-vnc.daemon.
2023-10-02T21:37:26Z systemd[1]: Started Service for snap application ubuntu-frame-vnc.daemon.
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3253]: + snapctl get daemon
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3231]: + [  = true ]
2023-10-02T21:37:26Z ubuntu-frame-vnc.daemon[3231]: + snapctl stop ubuntu-frame-vnc.daemon
2023-10-02T21:37:26Z systemd[1]: Stopping Service for snap application ubuntu-frame-vnc.daemon...
2023-10-02T21:37:26Z systemd[1]: snap.ubuntu-frame-vnc.daemon.service: Deactivated successfully.
2023-10-02T21:37:26Z systemd[1]: Stopped Service for snap application ubuntu-frame-vnc.daemon.
```

The same occurs if using `22/edge` as well.

If I manually enable the daemon, with `snap set`, the snap reconfigures and runs as expected:

```
2023-10-02T21:48:04Z systemd[1]: Started Service for snap application ubuntu-frame-vnc.daemon.
2023-10-02T21:48:04Z ubuntu-frame-vnc.daemon[4732]: + snapctl get daemon
2023-10-02T21:48:04Z ubuntu-frame-vnc.daemon[4710]: + [ true = true ]
2023-10-02T21:48:04Z ubuntu-frame-vnc.daemon[4710]: + exec /snap/ubuntu-frame-vnc/211/bin/wayland-launch /snap/ubuntu-frame-vnc/211/bin/graphics-core22-wrapper /snap/ubuntu-frame-vnc/211/bin/ubuntu-frame-vnc
```

Based on the way the document is worded for daemon being **the default**, I expected this to "just run" after installation without having to manually set `daemon=true`.

### PR DESCRIPTION
**Pull request by Saviq**
Fixes #11

### CODE REVIEW

**Review by AlanGriffiths — COMMENTED** [review]
This is more elaborate than the install hook in iot-gui-snaps or ubuntu-frame-vnc, is that necessary?

**Comment by Saviq** [comment]
> This is more elaborate than the install hook in iot-gui-snaps or ubuntu-frame-vnc, is that necessary?

I started from Frame itself:

https://github.com/MirServer/ubuntu-frame/blob/main/snap/hooks/install

I suppose it's nicer to not ever start the service than to start and just stop it again, when on Classic?

**Review by AlanGriffiths — APPROVED** [review]

**Comment by AlanGriffiths** [comment]
> [](https://github.com/MirServer/ubuntu-frame/blob/main/snap/hooks/install)
> 
> I suppose it's nicer to not ever start the service than to start and just stop it again, when on Classic?

The configure hook should run it before it starts anyway

**Comment by Saviq** [comment]
> The configure hook should run it before it starts anyway

It's not clear to me that's the case…

https://snapcraft.io/docs/supported-snap-hooks#heading--the-configure-hook

Other hooks (e.g. `install` `default-configure`) explicitly say they run before the services start, but not `configure`.

**Pull request merged**
